version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: evolution_db
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost -p 5432 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 20s
    networks:
      - evolution-net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: ["redis-server", "--port", "6379", "--appendonly", "yes"]
    volumes:
      - evolution_redis:/data
    networks:
      - evolution-net

  api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    expose:
      - "8080"
    networks:
      - evolution-net

volumes:
  evolution_instances:
    external: true
  evolution_redis:
    external: true
  postgres_data_v2:
    external: true

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
