version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: evolution_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d evolution_db || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server","--port","6379","--appendonly","yes"]
    volumes:
      - evolution_redis:/data
    networks:
      - evolution-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    # Sadece debug için dışarı açık; tamamen proxy ile gideceksen bu kısmı silebilirsin
    ports:
      - "9001:8080"
    expose:
      - "8080"

    env_file:
      - .env
    environment:
      SERVER_TYPE: http
      SERVER_PORT: "8080"
      HOST: 0.0.0.0
      SERVER_URL: "https://api.nationalaicompany.com"
      TRUST_PROXY: "true"

    volumes:
      - evolution_instances:/evolution/instances

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"

      # HTTPS (443)
      - "traefik.http.routers.evo.rule=Host(`api.nationalaicompany.com`)"
      - "traefik.http.routers.evo.entrypoints=websecure"
      - "traefik.http.routers.evo.tls=true"
      # Eğer Coolify'da certresolver adı 'letsencrypt' ise aktif bırak; yoksa bu satırı kaldır
      - "traefik.http.routers.evo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.evo.priority=100"
      - "traefik.http.routers.evo.service=evo"
      - "traefik.http.services.evo.loadbalancer.server.port=8080"
      - "traefik.http.services.evo.loadbalancer.server.scheme=http"

      # HTTP (80) -> HTTPS yönlendirme
      - "traefik.http.routers.evo-http.rule=Host(`api.nationalaicompany.com`)"
      - "traefik.http.routers.evo-http.entrypoints=web"
      - "traefik.http.routers.evo-http.middlewares=evo-redirect"
      - "traefik.http.middlewares.evo-redirect.redirectscheme.scheme=https"

    networks:
      - evolution-net
      - coolify

volumes:
  evolution_instances:
    external: true
  evolution_redis:
    external: true
  postgres_data:
    external: true

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
  coolify:
    external: true
    name: coolify
